/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nats.io;

import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertTrue;

class NatsServerRunnerTest {

    @Test
    public void testConnection() throws IOException, InterruptedException {
        try (NatsServerRunner server = new NatsServerRunner()) {
            assertTrue(server.getPort() > 0);
            assertTrue(server.getURI().startsWith("nats://localhost"));
        }
    }
}
