name: Build Release

on:
  release:
    branches:
      - main
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_EVENT: ${{ github.event_name }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Install Nats Server
        run: |
          curl -sf https://binaries.nats.dev/nats-io/nats-server/v2@main | PREFIX=. sh
          sudo mv nats-server /usr/local/bin
          nats-server -v
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build and Test
        run: chmod +x gradlew && ./gradlew clean test
      - name: Verify Javadoc
        run: ./gradlew javadoc
      - name: Verify, Sign and Publish Release
        run: ./gradlew -i signArchives signMavenJavaPublication publishToSonatype closeAndReleaseSonatypeStagingRepository
