name: GitHub Push To Main Actions For Nats Server Runner
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: "MERGE"
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      GPG_KEYRING_FILE: "tbd"
      GPG_KEY_ID: "tbd"
      GPG_KEY_PASSPHRASE: "tbd"
    steps:
      - run: echo -e "PUSH/MERGE to main"
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build and Test
        run: chmod +x gradlew && ./gradlew test
      - name: Publish
        if: ${{ success() }}
        run: ./gradlew -i publishToSonatype
